name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH access to EC2
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        echo "Installing Docker..."
        sudo apt-get update -y
        sudo apt-get install -y docker.io git curl

        echo "Stopping old Docker containers and removing images..."
        sudo docker ps -q | xargs -r sudo docker stop
        sudo docker ps -aq | xargs -r sudo docker rm
        sudo docker images -q | xargs -r sudo docker rmi -f

        echo "Cloning latest code..."
        rm -rf my-devops-proj
        git clone https://github.com/NisargaSavadatti/my-devops-proj.git
        cd my-devops-proj

        echo "Building new Docker image..."
        sudo docker build -t php-app .

        echo "Running Docker container..."
        sudo docker run -d --name php-running-app -p 80:80 php-app
        EOF
